/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConexaoBDjava;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HOUSE
 */
public class TelaLogin extends javax.swing.JFrame {

    ConexaoBDjava con = new ConexaoBDjava();
    
    public TelaLogin() {
        initComponents();
        con.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butaoEntrar = new javax.swing.JButton();
        butaoSair = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        textodoUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textodaSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        butaoEntrar.setBackground(new java.awt.Color(51, 255, 51));
        butaoEntrar.setText("Entrar");
        butaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(butaoEntrar);
        butaoEntrar.setBounds(240, 210, 70, 23);

        butaoSair.setBackground(new java.awt.Color(255, 0, 0));
        butaoSair.setText("Sair");
        butaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(butaoSair);
        butaoSair.setBounds(400, 210, 70, 23);

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsuario.setFont(new java.awt.Font("AngryBirds", 1, 18)); // NOI18N
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(240, 90, 70, 30);

        textodoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textodoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textodoUsuario);
        textodoUsuario.setBounds(240, 120, 230, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("AngryBirds", 1, 18)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 150, 60, 24);

        textodaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textodaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textodaSenha);
        textodaSenha.setBounds(240, 170, 230, 20);

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 270, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ainda não é um Membro? Cadastre - se");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 250, 250, 15);

        fundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/519509 (1).jpg"))); // NOI18N
        getContentPane().add(fundoLogin);
        fundoLogin.setBounds(-10, 0, 740, 430);

        setSize(new java.awt.Dimension(744, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textodoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textodoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textodoUsuarioActionPerformed

    private void butaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoEntrarActionPerformed
          
        try {
            con.executaSql("select *from novocadastrodeusuario where novonomedousuario='"+textodoUsuario.getText()+"'");
            con.rs.first();
            if(con.rs.getString("novasenhadousuario").equals(textodaSenha.getText())){
                TelaPrincipal tela = new TelaPrincipal();
                tela.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Senha ou Usuario Invalido");
            }
            
            // TODO add your handling code here:
            /*if(textodoUsuario.getText().equals("Renan")&& textodaSenha.getText().equals("1234")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
            }
            else{
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha invalido");
            }*/
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Senha ou Usuario Invalido"+ex);
        }
    }//GEN-LAST:event_butaoEntrarActionPerformed

    private void butaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butaoSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormCadastro1 cadastrar = new FormCadastro1();
        cadastrar.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textodaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textodaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textodaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoEntrar;
    private javax.swing.JButton butaoSair;
    private javax.swing.JLabel fundoLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField textodaSenha;
    private javax.swing.JTextField textodoUsuario;
    // End of variables declaration//GEN-END:variables
}
